# -*- coding: utf-8 -*-
"""bank_data.ipynb

Automatically generated by Colab.  
 
Original file is located at
    https://colab.research.google.com/drive/1zTZpBF_oteYI9JC31OPA7g0gsg5LbD3_
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv('bank-full.csv', sep=';')
df.head()

df.info()
df['y'].value_counts()

df['y'] = df['y'].map({'yes':1, 'no':0})

df = pd.get_dummies(df, drop_first=True)

from sklearn.model_selection import train_test_split

X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test) 

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Report:\n", classification_report(y_test, y_pred))























