# -*- coding: utf-8 -*-
"""x-ray.ipynb

Automatically generated by Colab.
  
Original file is located at
    https://colab.research.google.com/drive/19SAdLHiy9FBx4jZK1MnjCFeahf-6rCaf
"""  
   
from google.colab import files 
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive')

zip_path = '/content/drive/MyDrive/Archive.zip'

import zipfile

zip_path = '/content/drive/MyDrive/Archive.zip'
extract_path = '/content/dataset'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzip Done ✅")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

img_size = 150
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    '/content/train',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

val_data = val_datagen.flow_from_directory(
    '/content/val',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

test_data = test_datagen.flow_from_directory(
    '/content/test',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

import os
os.listdir('/content')

train_data = train_datagen.flow_from_directory(
    '/content/dataset/train',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

val_data = val_datagen.flow_from_directory(
    '/content/dataset/val',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

test_data = test_datagen.flow_from_directory(
    '/content/dataset/test',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

test_loss, test_acc = model.evaluate(test_data)
print("Test Accuracy:", test_acc)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])
plt.show()

import numpy as np
from tensorflow.keras.preprocessing import image

img = image.load_img('/content/dataset/test/NORMAL/example.jpeg', target_size=(150,150))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

if prediction[0][0] > 0.5:
    print("Pneumonia")
else:
    print("Normal")

import os
from tensorflow.keras.preprocessing import image
import numpy as np

# Get one image automatically
folder = '/content/dataset/test/NORMAL'
img_name = os.listdir(folder)[0]

img_path = os.path.join(folder, img_name)

print("Using image:", img_path)

img = image.load_img(img_path, target_size=(150,150))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

if prediction[0][0] > 0.5:
    print("Pneumonia")
else:
    print("Normal")





